apiVersion: ENC[AES256_GCM,data:ScU=,iv:aTBagI3nFcyABF75mTqbVkGc1Rh+S+kLDJYb1QnX46w=,tag:wIKTmFFCWD/OHlGNzXfa9w==,type:str]
kind: ENC[AES256_GCM,data:OTk/ERDm,iv:eTIQ2GyUT9ePxe0NOfr493mFJi3RMUo1GdAb2936gsM=,tag:tP140YRVGjXihiFMY65sjQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:HNwHp84FSvZj,iv:iIj6T9idXzVP3yENBngMsxMuslnomS5jvNQxi5ZltDw=,tag:Hi2wmWcKQH/GzLSkMVWp6A==,type:str]
    namespace: ENC[AES256_GCM,data:LkgbzA==,iv:M8HBnziYTmrtRGysXVHEOCpK+UiTbKYN678enaCvCl4=,tag:pP3oInEi3Un+03blWGivjA==,type:str]
type: ENC[AES256_GCM,data:lh3n6ulq,iv:FAtpFpe7r/rSIKxNSXVlSr8J8HF4M+y5aynwsoQQ4mA=,tag:r1ql4SYTbV1E7KKfNuycwg==,type:str]
data:
    KC_DB_PASSWORD: ENC[AES256_GCM,data:HjucharX6hI=,iv:wyVOvAEJ3Bc9aXxlJ74kjhr+m0O0ZdCp7i9EOeFeyqU=,tag:jkdKl0QUx6rvFRGTeY+OJQ==,type:str]
    keycloak-admin: ENC[AES256_GCM,data:udA3+U3jhrs=,iv:fClkluBxTGTFbJqTmEFoqx+NRugnjkur/0KdFOgclj8=,tag:MrNOxuJcpE0Q5YydK6Q1rQ==,type:str]
    keycloak-admin-pass: ENC[AES256_GCM,data:X/JePQ==,iv:Bg9y35XZ2keDeJUNysTKDVY35OtsqPbi4om8s6IMn8c=,tag:K9qMUIvcsAPcna9r3DyMAQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cuu6f3wweappd2xqztvey2d8kxz8a9yfhkzr52t3vw6wz7q6w43suavf89
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6eFBMbWs0U1hmNjB3NFMv
            WWF6eVN2cWhKditiNjJZa1YxSTZsS2dIcVFzCnd0TFhvb1gvWWdFU3lxZ0tDYkRs
            ZWFOeFl6MUhuTU9oK0RjeUJLWk5uMXcKLS0tIDRneFBTYjdNelJlQVRsdGYvQkVm
            bmMzdFBJcEhMdUg5SXk4MVhwekt0VE0Kx2i1K4pcx4V77/orkNCRpiP7NnBxovTf
            vb9xq1EOzjeTQJsYo6npk3GEi8WNtz5eqjO+0Gb2bDme2LGStdKqIg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-05T16:08:23Z"
    mac: ENC[AES256_GCM,data:jIvBEAyJDLrh5mmfL5/skllIAn7zgLmfyQ66FWIOpGkiqdpLvLZgCCR1A58p6oIkyxWbOzZ2FkY69NMfEa44h3WnsEd+hPzKZN+FQ6SWlamxTavh/qDuYrF3yd2XUr9ac4IXyrBProvdeZ+20nJ8NdKC8dWc4fRy5CN+kAp7a4E=,iv:ZdojrpOSE6ocA7v1WNDjyc8yTylsztV27sGwuIBiNCw=,tag:Dq5+kwCbYhZj6JvOcXqXDw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
