apiVersion: ENC[AES256_GCM,data:31I=,iv:rywmasEQwC5qgKtr/WoCFX8EUVopXqasYA3l3E5+qG8=,tag:sEWk9TaSdgOhCy8CNzFQBA==,type:str]
kind: ENC[AES256_GCM,data:4gzZnaqO,iv:jQFkb1npcHq2Ymn4ueqi0j+jp/2ipOsqIJRG7G8YS0o=,tag:bl/csmnfjLjqSlF94J/kzw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:kW+1uCENDU2S,iv:TT8RWQoP2bxFebQKmv1GKkVJDp+zQ/Dee9L8sG/TENc=,tag:wwrWrl0JbnUlLHjf/W8Oiw==,type:str]
    namespace: ENC[AES256_GCM,data:vS2a+Q==,iv:V48HdTSpl9IEishyqVapgsvY6cHWKHDGxDAkHmEh0Ic=,tag:nQjYPdezmuaVIS1B+WIl3g==,type:str]
type: ENC[AES256_GCM,data:ZzVjF8lo,iv:2y/46w26qIM0JU7AH5KYTXfwoXi1mahLd/oz87N/N50=,tag:vfNXF1y0uAEA3mGpc/I82Q==,type:str]
data:
    KC_DB_PASSWORD: ENC[AES256_GCM,data:qugxLhWMLQY=,iv:uvHeTubn8WPf3SsSJTp/NRFeOjSG2/PStSz3pbceDQQ=,tag:b6FqLdvY1ePmMn87fhLKQQ==,type:str]
    keycloak-admin: ENC[AES256_GCM,data:nXh3grvkG7o=,iv:H2YbgRA4McOKc21lUMpMFoj0v1bHrsoAQLaQQoob4N4=,tag:3qIl0M8h0jOKGjR6MDmZkA==,type:str]
    keycloak-admin-pass: ENC[AES256_GCM,data:aYgcKw==,iv:aCbu9rG9qv50pC317ppgcnJEoVSbaqhSUAeEUBzzpnw=,tag:jk+coqEtMG0aG6x2rg919Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cuu6f3wweappd2xqztvey2d8kxz8a9yfhkzr52t3vw6wz7q6w43suavf89
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPTlc5T2twT0pCbDRSdGds
            c1FGU0RabWM1UVcwTGFsOW9LbGNSWkxBZlNNCjVIcUpvaFF1N1pEZDJhaHBIVnVh
            UVZicFdxSnZIeW5reG40Q0tGYWY1a0kKLS0tIGZ2RERlcCsxVzFPUDFHbkRaYXZP
            VjF2MWJaL2RFL3VGcjlYcjkyV2txUzQK6S93QRLGErvQIye0Jr9j/Kl/CTZ06O7l
            G+g+X/oAx1WrbS3YNnPufQ96/I5cuMnLKftX3hM5rESXvyu2ibv2pQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-05T16:33:49Z"
    mac: ENC[AES256_GCM,data:ZEIu6+KRTGErSq2cRwcyilqotiiHgmxfXLKZ5QowVVoWEaB0VaOMayMJXXe7sOexXcCHXBlAQvuKu/iAd7/btce+568lwMNc7nG1xgIPuOkDo+tvUFkZkiiPfK8pb+IYoztEtiywS3uAp5KVhBVrNKxb1qReOpjul+gdaE87Oi8=,iv:mJ4AtHcTNYBS8Sbw3o6cB7AGjsIR2IyOW4HhY9dLeYs=,tag:djP2OJNXSSEAduUdw97KkA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
