apiVersion: ENC[AES256_GCM,data:1EM=,iv:eKiYyngsAyckOP7yQFtCHPCqF+jOwFZdp7N4123JOjs=,tag:Lxuxrun+BDJUtm7AAGaHlw==,type:str]
kind: ENC[AES256_GCM,data:hXjq3Hhu,iv:ZuUlNQnhaO64ARg/VrbYDdIu0Luat4bH6MnRdUIrzGg=,tag:OFVz5hbKVoRg4f37beZENg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:YGh7/b56rIHZ5tMObheYtB8k4Q==,iv:8cRoVOGLbsUbsRzq7gYBWcnQ+PhlCm2fC6k+OBKNYGs=,tag:WoA/WGOtriBLd8zMtMnYow==,type:str]
    namespace: ENC[AES256_GCM,data:5hy8knd9KfCF1r7U,iv:DgZ/7MjR77neDPGoJzrPu17upQDHjyDJBqqzEFxaBwY=,tag:hZTrCs+Cq/3yNgclsyUTAg==,type:str]
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: ENC[AES256_GCM,data:dnitTV8=,iv:GEliWVYL1SQ1McJFJ4+B0bM/0H4h8y4bfl/iqxtUwB4=,tag:XTgR0m6onjLt16SdexwsSw==,type:str]
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: ENC[AES256_GCM,data:92fMaA==,iv:rRxEr/iMQUxpXUm/xPZV2Bz8hljZKo1mDhkUN9M+Xd8=,tag:rVRhQ/ZOG+8GZi9BtgLDTQ==,type:str]
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: ENC[AES256_GCM,data:KM3sEA==,iv:uud5xXQDOZudU4qwFArrQWSHKb9t3AWiKs5cxr4pp7g=,tag:eJvsZRDlAhoKQLm1QpRfyQ==,type:str]
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: ENC[AES256_GCM,data:JefOmg==,iv:HxMD1Jmg+v4WvgsAAtKX+yHPI1F+utfoKbEZkFVRYaA=,tag:zXLWBReC5RYCl66bTDo13g==,type:str]
type: ENC[AES256_GCM,data:k0unvT1Z,iv:tPhZfrJXOgXu+nqIuEMF7VJW5tKxrYFPyTNIFZBKvI8=,tag:9BUkDmFvkDXWbt2Nuyn7/w==,type:str]
data:
    password-key: ENC[AES256_GCM,data:+JpPcxgpXOZObO/H,iv:PGZRMveAKOPcK3cukgQR5REg8wxhW5iCUsO8ki/MLaU=,tag:01+HzM5jkaxuwM7v0K50EA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cuu6f3wweappd2xqztvey2d8kxz8a9yfhkzr52t3vw6wz7q6w43suavf89
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsU3BOYXVBbkVYZTBWK2Z5
            aWRWUnFrYjZtNVcxdWFqOHEycjg3OXpXMmxVCkVML3ZKNHdHVlV4MC95WHhjdmxq
            Wmd3UDRrRXdPUGNGVktUSnJiZkEwMDAKLS0tIDhjSU90M3AyYWdObm41SFZMQ1JC
            UjlRVmRSNW9WZUZRQnU1NWdBWHd2bFkK8mubgviA+uHvxCIuXqhn8MgI+6P1QhoF
            90F+vlYWK1jjgJnKHTIukCbXN2v3x7yZybeesNAU49OBpNvm1ylgLA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-05T16:35:35Z"
    mac: ENC[AES256_GCM,data:cXqtFtcU+aR5QbCxaMGfQdM/Y1bX2yeK16lwoVQFIAk8wqsQygdzw3x9fbTAzr5xe2/BT4rUet99b3f9WwPHJjjo4oNp9kpt8Qe4ft6OcmgR+a1pWFILmXPsGj3yJW4xe1TX/XfBnbqnQ35/VYoRTHwXVNjCcsaoECQ8xjjk5YU=,iv:THOInJ8cbsxUEZlCS/aw3QosL9greSqcIMXbPgkcMGE=,tag:SF/BZZSrmYCEL2BGVb6WJg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
