apiVersion: ENC[AES256_GCM,data:Xqs=,iv:p+GiI1ESnnuZRAyu7zI27Y/EgZU0NL2yKprd7uyIOnQ=,tag:c95boD7ZUDVnBtp8EgRuLw==,type:str]
kind: ENC[AES256_GCM,data:bYHUEBG7,iv:VkYUFIoRqeOzqgNEREJLLJzuNB17Mh7TchOXOEr+3b0=,tag:ZiSWW5A/nCvQxjr0r8wgGQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:C5rFceEG0QHUnjCQgFLn80hIqg==,iv:vFRLIlA04ANjOt1uoGZBjYKcrVdixtQR24mMZXrsXqY=,tag:GuK4IB2tO+2OZtht27MqHg==,type:str]
    namespace: ENC[AES256_GCM,data:EvO3AYZUyQ7Vkq3c,iv:oNUXFEd6R7N35laubiuBea2yMjf1Z+0wGPn8LCzv7Sk=,tag:pqezd+L9zrYuB84J30P7GQ==,type:str]
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: ENC[AES256_GCM,data:2DMsww==,iv:dUKLzDAMnqUvCIr9RrM0HSBMXdLi8A9u0m8z5DvviA0=,tag:UiMRtRa6VYigWCt+LKwvfQ==,type:str]
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: ENC[AES256_GCM,data:iAtX2g==,iv:cwjBFAYO+niwhxaPUlzC1RAwk1HCRl06HQbf1Muz5Jg=,tag:t3IpefasLulZ9HeOh98psg==,type:str]
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: ENC[AES256_GCM,data:V7dvTw==,iv:tckn7yBX8Mobj4acxmiOuMYBTeq0uuGtzV/DKtqPWJM=,tag:39z5eK4iT+VVhwGAVShYWg==,type:str]
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: ENC[AES256_GCM,data:oueusA==,iv:SsgxqXgsl6V0z/uYTDH0jz0Y/L+L1ubGk3+Hcxo5uo8=,tag:Cnh+Ddc6W3CLflIHE8xNYA==,type:str]
type: ENC[AES256_GCM,data:LQG51BtD,iv:C3S69BSsC5rPnmSoIW2hbtw+8bTyBWxeMzKc6lqorYQ=,tag:XJxVCViI8TZLN5YplUci5w==,type:str]
data:
    password-key: ENC[AES256_GCM,data:CD+lL4uonx14Yi9h,iv:Qx/fMA2yLXjTOQbmls7ggJZ03vKAvLHI7k/NDnBiSOM=,tag:CMIeGINkRfMOgss4NWHw2A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jh9mchm2yn0fnz74t8njjagqsq7rem6ezfrz26mvvvnu5dlk7v7ss57cc7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByb1FUdjBPc0htTU1oZjJX
            Tml0VkJ4d2xERzVGWE9LZGE4aG1KWFNyY0FnCmFZUHE2eFFWZkxsd25mTlpZNHhH
            L3Z3REtneXgvTG5CRERpcU9PT0VLYmMKLS0tIDYxWksxS1lWMXFCRkNpdzlOYjg5
            dFNtQ21TSXJ6NmlxOWFCNFc5NUwyUkEKhwghISn686uWae7HMjLb798dvCJhifww
            ODQPZ4WRyiHA2Rf7U9WJkb+VUKqBdhrXYVWhE2uLdJZV5lGkPdE8zQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-16T10:05:04Z"
    mac: ENC[AES256_GCM,data:/skIOTAFTrJASxEUgMdeR5qrgPl+4qaIMQGfhjDBXgODxnfNBTnW9M3iWXEJZhTSJn2YD02sazwDFmDPWfIPmbzR6hSI2JpiIoENPsGfoYC+9YGdizwCJM0JXH0wejDQ2GYlFMSG3igOx6kc7ubTW1qRksD7qdb+zw24jKyGcsM=,iv:xaDBcU2h3bW71G0s2IENhx9cFu4vSWyxSs0Dfmf5pbA=,tag:p+Hbt2dChx/Z5TDV2EFHAw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
