apiVersion: ENC[AES256_GCM,data:6zg=,iv:2fbutIyLWx5SK0USGU7cZn58mxsxWNBdcdeeiSTT2vY=,tag:NnPeSaBHr/auv4fTd4sezg==,type:str]
kind: ENC[AES256_GCM,data:+mhxObnT,iv:W3fsnzXI0mpwFOEGtc10umziXSsYn11bEsxFYMPNrcU=,tag:eAclUu+ntP6JGbfnxW4SmQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:QRtnbCQqOm2HH0Ivz+FKSkIwRA==,iv:djUgI8aNKtiGJntY4HBXlr4AS4KkokvSey4HwkI5PwE=,tag:JTTCWMDv1kHQwlO3XLjuUA==,type:str]
    namespace: ENC[AES256_GCM,data:BLIhiNKi59DH65ex,iv:6JVMGUDr1Tgg1oPlepzIwII5Yz2Kcn5LxbqHLJZ4gMg=,tag:l80jWJ+C2qDBmpQitf+R0g==,type:str]
type: ENC[AES256_GCM,data:l/y9nezu,iv:04QK5IdVziKQy+xTiC5HC9yaByWtk3mcGBwqZaTYEg4=,tag:/rPEEaYvQ7k1KNCIkO21nw==,type:str]
data:
    password-key: ENC[AES256_GCM,data:H7r06WSV94nAdIX3,iv:UjLksUw8i8UGrFcptUD9dchl9xhQ+a+tbi1+9F4Hjcg=,tag:bIUCsCWvMcOElHzgvy/BxQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cuu6f3wweappd2xqztvey2d8kxz8a9yfhkzr52t3vw6wz7q6w43suavf89
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEQlFUZ2lmcGw1R0hwWklz
            elV0dG9Fc3Bmd0hKRUswalFHNUJhNjF3OUU4CjZQTTBDME5RZHFEQkczbkU0dE9N
            bGJBUURMeEV6aFMxbG9mSUVna1NqL2cKLS0tIDVMKzR1ODZPNzRxTjNVbHIxTzhu
            eURPS2dYOGgwb3BmZk9Fd3V5WWZIRGcKlKk4ZnYBvfg2bxThzuIpWaEG8xk67Pzv
            /Ep+syrzXdXY6Hr1zWxNOYvIMKxXPtYGBE50qgTZBaQUyJzrMQhWWw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-05T13:32:28Z"
    mac: ENC[AES256_GCM,data:PF4K74awfqk191fvczH32OiU6MFZrxH/RDRYAJ8rJbOLlse92IpgnoybbS+uYO4q23k/Jz7iNSi3u4p6N+ktFkBNtiXQewQh2RcuN+TV9BJoz1j+AXs+cjjO8X9J5yvuUvZTXocsvcdEE8uvFPHsFUwKoCJh1YgwaGI515JM054=,iv:SEigZ/9uDIE8H0Nl8LZ0qz36vmyQe+5RmnkPFz5tpW0=,tag:daZjZyGlbbxkPWXtEykVdw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
