apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - lernapp/lernapp.secret.enc.yaml
  - flask/flask.secret.enc.yaml
  - psql/psql.secret.enc.yaml
  - kk/kk.secret.enc.yaml
  - monitoring/monitoring.secret.enc.yaml
  - jks/jks.secret.enc.yaml