apiVersion: ENC[AES256_GCM,data:USw=,iv:Jjnz+lDVSFerGQIqxUfMUun7ZVCfuM+LJPj4Qop929I=,tag:gf7jfUFJ+tvHRded4Awrzg==,type:str]
kind: ENC[AES256_GCM,data:YmOITbLO,iv:e0UQzPYW8ESpYizBJzSDkmyPNsgWHqhBlcYgi3t8JE0=,tag:QRo0SJLXn64swVdxB24gUQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:+qmadloajKFAHClR9ZYq,iv:T20oIX0mWLYKOTC2OJyYjNqfA2uPOTIVQ+LbACVBKOA=,tag:+RqFNF3nTTxxxGJyNVkwng==,type:str]
    namespace: ENC[AES256_GCM,data:sA4sVQ==,iv:DhfnszLPSwt94gxY+Sobtt/EpEZoJQZ6hX0Pw5i3tMY=,tag:ws1IadwZQPFcC6wyGNB4XA==,type:str]
type: ENC[AES256_GCM,data:1VtagMTu,iv:Ite86NYUrC4pT4L5sjNV86P9dBN8MdYBpnQ90n8VM2A=,tag:WeP9rPCGQeuVXKCIl9cc8Q==,type:str]
data:
    postgres-password: ENC[AES256_GCM,data:FvQyxCBe4SbllzH+ER4IxQ==,iv:VchBR/tV8ru7ErRqsDD9IDm3AH0DCaNPbd9FkqpyMj8=,tag:21THUvurOljZZF3e3txfkw==,type:str]
    KK_PASSWORD: ENC[AES256_GCM,data:Slxup2yOquE=,iv:H2tHh3IXKXM8TULRgwJF1biOg8DUHvPmoOrNU7CWup8=,tag:1MeElKX9USp6tZu23gptEg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jh9mchm2yn0fnz74t8njjagqsq7rem6ezfrz26mvvvnu5dlk7v7ss57cc7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwSlZKenc4Y1FOczcyZHcw
            UGQrb2ZMMHl0dXQ5bUdvbnRaN1FUTmhWVUdnCkNnV1Q1WFI2TFp0MzBvWUZEeGxI
            WDBCZ2hGQW1iVFpGZ0QwRnhnOGo2aXcKLS0tIG16T2NTRTN3UEp4MUw5bG05QkR5
            Rm14OFBtRGZ2b2tZTEZoT0puenZISW8KvomEWARE5R6qQEDm66iUBU4GVW9vnwhK
            xd8WbsrIjdnF/yIu+igP5IsEBNPbw5CCKSUvZzBW424IsyRe1QHY2w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-16T10:05:05Z"
    mac: ENC[AES256_GCM,data:Q3Rb1DspBNHRQFTQmbxjoP2ma/20OUEHVvTL8fEDi6ZRAKTpwBLnokd/mg0Q+AtRJzMcx3ItmPMVcQLPjn7tbKH1YYzaBsK+zKG14fRRf8lT8yp//5STYO6pQvxZ8yVCTH0RxGTi/cWnT6245WlR3KE6IeC2XT41VdHV+hgEzVU=,iv:sLJqX0SsXMvZWBclUtYAtsiedDBx0hLbRvKJxcdxtQM=,tag:Xd1N85Ua74eUI14U5xdW2w==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
