apiVersion: ENC[AES256_GCM,data:1bM=,iv:W8uU0ygxFx3TcvNOW08eV1vc8HHUXyTXyLiXTASRfVQ=,tag:C9WW9as3LcMo0u8ZSKFnug==,type:str]
kind: ENC[AES256_GCM,data:uRi4837l,iv:ZOEfLEUcQLh0DoAlSFaphlepJ/gk3ulz/6W5eS5sEsg=,tag:rAPOWhFN51lZcKlWOOQXPg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:kKKzyTfkME0NOh1ErJxN,iv:bq6WKZUEbDoYxKE4xj4WdbcFN33s0uPwGqukS4jG7d0=,tag:Fx+WON0C4OADkXfUyUQA+w==,type:str]
    namespace: ENC[AES256_GCM,data:xDFGrA==,iv:2fVo1xRrryvr9HDEp/nKmQncZKDjhGZxvG/AjcLDGrY=,tag:rK+BH/+HpYUZrmte3rOhqg==,type:str]
type: ENC[AES256_GCM,data:nBYhAo/Z,iv:s7Q05mIftcZHKGDdM6jzFer985nO0TPqmtgTmziH710=,tag:pJf13ZsemrR5NAKN9BqjnA==,type:str]
data:
    postgres-password: ENC[AES256_GCM,data:4c2/XqNikBj2So1jtme/8g==,iv:zsGCVKTG0JHZ6TDNe4TER51n6uJ11hSBw64s6EJ9IOE=,tag:Tbxa8phdjMPcY+yuYPxVqw==,type:str]
    KK_PASSWORD: ENC[AES256_GCM,data:l5KAP326LpA=,iv:kt1668os3BqTK32ioa8R6cwNtL+fuk6sGenZLsp38to=,tag:idd2MKq/kXWrmOgjNq706w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cuu6f3wweappd2xqztvey2d8kxz8a9yfhkzr52t3vw6wz7q6w43suavf89
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyVldZVTlqSVpjZEhOcmZU
            UktPSXpyb2orcXR2VHdicWlNSGJnS3NPWVVNCkl0REhwdVl1ellCTXRHMTJRQ05V
            Z2U2SkxWcm5maVRQRlFGckFlOC8yZW8KLS0tIFRUeXI2QnhJUi9kYzZZLy84NjBK
            OTdrN05jQXdZUTE4MDErZ05sSGJLOGMKJpO1pcdsHyGSG1x90pS+zWGLW5oGh2JG
            1fslq8O6byYdu2SKJ90Xlnp/vk0gQR0mrY63yYXNq9O2wkT4Qm2gwg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-04T13:41:36Z"
    mac: ENC[AES256_GCM,data:fh7lAnByuDIi44U3aDy3YEJUFlriOVdRSDLwKItn94PaVtgVcmfo/nQHZ7VfQ56rHooz8qoYJ6usAJgxFoH1LSiZOWZhAR40waqy0m4OCNGvGwd2notUH+p6Um5/cauHaiGNouzGY5KwV784EerKoxiUVtTK+e4oqucGgREMyZ8=,iv:Yo77qMAshRapOeo1BvllZ/NUXPHE/Jac9LFD/nAa0bk=,tag:WUdGA4ZEbYC2LVeWUQeIUA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
