apiVersion: ENC[AES256_GCM,data:LUw=,iv:fr+MprVbTOPvONRGCt2E+8g+o2heWzDq429SJAxNprw=,tag:YPEMDd237p0U25ynwAvJsg==,type:str]
kind: ENC[AES256_GCM,data:3xkbPmAN,iv:h6/b8EihCaU7wmlNKbFZgQzsDW9NbtDyteOKYfT8gXU=,tag:eZgNA2ZzdrTPEPKKJB5Cqg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:W5G56bZzbZK07N8lnZQl,iv:+fn5h7NB6vhqswBbA1RuP/oW/XO9+fx5xT8vSdcpCnQ=,tag:Cb1VKpNuedi0+iIx1DJaDg==,type:str]
    namespace: ENC[AES256_GCM,data:2hgh6Q==,iv:zZHk9GfV4GJ5CInqDIVgfSrd5xk+TTqd+YTpRLMX6Ms=,tag:Isi6BU5sS23WW4+c0aCDzQ==,type:str]
type: ENC[AES256_GCM,data:pl8VxDYF,iv:x53LmOwipOCHXLyKzI8mJsDXtsGeW1OHgS0C7G25shk=,tag:nw83xj7dHNo6G7fdrG4k+A==,type:str]
data:
    postgres-password: ENC[AES256_GCM,data:XlJvugneXF8J2AgUfseluA==,iv:4ueurckc4oVY01kVwrYbKpKCKfqkvX0hXV2/CZl7oVg=,tag:XZoF5R2d8dIbA1xyDIl0gA==,type:str]
    KK_PASSWORD: ENC[AES256_GCM,data:UOg+dxsLQeY=,iv:Lu8T4a+V2b7p8+pp0yDyZJoFFTxHnUQ6/x3m2EtOiGQ=,tag:ooXB0HGdCEXzKqlmRGEMzA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cuu6f3wweappd2xqztvey2d8kxz8a9yfhkzr52t3vw6wz7q6w43suavf89
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvN0pKZllxQTRiWFVyak0y
            ekhhSHRUaWV0RUE5RjJSQXZTbXhXN1pLa2g0ClhCRUYrMHd1TVJZeWJvWVZoT3RJ
            aSs5NzZnUkI4amUxL2lxTjMwYzl4SGsKLS0tIHNaRDJBTXN0b05QKy9raUdSWkRN
            dVROMW1WTEFUSUVEdEw4dmtzakltNkEKXHPLA0aapC71HaHT2yzgBgfuCTI1Y/9D
            2tYFffbjH2iYFxkjysyUYopiu+IrDv1ICc83hGfXVIw70ZeHOdByFQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-05T16:08:24Z"
    mac: ENC[AES256_GCM,data:nwOO7kY3XBW2wF4QoAD73WSFnVHcGSRwzOtHH9DSCAEPUdJ1MRTtDQ08DRE/KhXUnz29poiabWJ5uGWn/0n9oskzAL6qckfyAwDl1yhFUUUjlgVFvc4JszQaDp2USmuCsw7ZfyX7TT6X0mq4qxQjARzK0zF5fgW5zFaxRDSvzag=,iv:+9ENUhK6rgeEWulEXBsuiP949z2QUzD3iiOxiDvD4YI=,tag:rPr1kDgYvB79fpRaGbgHgw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
