apiVersion: ENC[AES256_GCM,data:Ypo=,iv:V9sJbWKYgedGhbpKcBbkBttnXndXgKPGo0V1TKPHVHA=,tag:27Jd6OESut6Yn40ulyc8cw==,type:str]
kind: ENC[AES256_GCM,data:8aCiIk38,iv:ccrEU4aKnRhbKCT3LwNYza/5htkXgpXmRYE8z/62G7A=,tag:xmDogp/RSaZCkO1MRNUUzw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:t2ahf8zRCRQ4kMh6FpkG/ek=,iv:SCqAkbAWtUqLdss5XyW3zr66qm62y0vVfaZze9eG3EM=,tag:RbeFSPr+at95fCvQXkRexQ==,type:str]
    namespace: ENC[AES256_GCM,data:BsUsjkKrDwNEfA==,iv:UwJbt4aQbojxFnSwnnNen+ZZmHvxlMq77TsI4g/du7Q=,tag:RPtwIRQ6x+c2Zedc7uKl7A==,type:str]
type: ENC[AES256_GCM,data:5/qYfNuu,iv:Yj+aO9UEcyvy5Rp6FJ3OikKfZ2tNJp7eiHfuydQuKTw=,tag:QR6lU6T9/pHxSngKcSwgXg==,type:str]
data:
    grafana-kk-client-secret: ENC[AES256_GCM,data:oGm0wUxtNd+7pqH8qc5j9FhI/7bx1Ebjt6GY3cUQPl3nK7+IW7CnL5H3vT8=,iv:vGpxUqIoB8up3dsuCgBq4DxdqOlWVACO34OLwuwbPes=,tag:6DQ4jXWEnoRCsFAJN29H+w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jh9mchm2yn0fnz74t8njjagqsq7rem6ezfrz26mvvvnu5dlk7v7ss57cc7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDZjlrVk8xK1FKSk8xYjFH
            R1gyb0srRGJuQlBYeVZHdHVGRDBuZFdUOWlvCjNQeGZ2N1ZvdTRSbC9RS0hvVjdB
            TnVLWlJvZkVmN0VqRHFiZlFhV3FnVlkKLS0tIGh2ek9BVTNkZ1R6K3hZVXBOcml2
            djRzeFBTcVNYdGRlb1hXcVJRS1ZTaEEKLuTfnkz9NhraANl9itkya+L652OT5mDE
            R8bXlNUN8tu8wm0K8RfV8QpZuutB5FKjuOHTjp89sY+aA9G1GH2jwA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-18T14:08:05Z"
    mac: ENC[AES256_GCM,data:+qQh7MMiLGnBBE/SRltKX0/juPbyCsK4bxjrgEzvc4TnFoCwzzkdIAOn3970S6b0wkY1eToRKEd77wKoZimbWD6zmpf7p7QMJkk3Idms/mEksc0lYR/JTm/I1KHoqYifRLKJtwBeezLJzzn4OalgYIZVRWUSa7T+tOb2EYTEcjI=,iv:DqekE1u6ygivTWsxLbkq9I3vHQFGcDcJS5He4wLGuMM=,tag:VIH8u9ZtKtEhokeTlB8zEg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
