apiVersion: ENC[AES256_GCM,data:ruI=,iv:dA6SOiisRHtAkDr9zyzkawQYdifqot7tRjf8M5zh8MI=,tag:Fst6Wtf3bQDBvKJ+qt37Kg==,type:str]
kind: ENC[AES256_GCM,data:kVYQcH1D,iv:Wz+UL2sScRhjuGg6UM00o4d+eKU+zS6wvtXeD23lejQ=,tag:OBU8dB28xR8ijbKj7wGoeQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:79O6H8oas+gw/JaU+JGjT3o=,iv:D7yaI7MPXdOnrsq9qHbOacX0B6Q6J7sdb4SXSGj0TN8=,tag:6N9Spim8cQFKgjfhFaziFw==,type:str]
    namespace: ENC[AES256_GCM,data:mlohi/u0Jgq/uA==,iv:M8M4RaDDfV7RANh2xiSSWaobHlRzGm0oA9ssolzD8Bk=,tag:im5+kMZVqwamET5qrIENWA==,type:str]
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: ENC[AES256_GCM,data:PZsbYg==,iv:740i1d7jkTZAG0R+KDQjDBfGLKrPcorOmEjyedbozL8=,tag:s4c/jcoEH/WqktfMNPcj6g==,type:str]
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: ENC[AES256_GCM,data:I4vKb92Ti2Y=,iv:MnBetjaWiTE4zA7zhEf+qUVJeVD6RzpwndZWJ8VsgtY=,tag:POUcP2KqyHuliiws6PRaVA==,type:str]
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: ENC[AES256_GCM,data:6bOtAw==,iv:kvcdzxUvaBccbsE3tTK0rnnGeiHfGPPuXv6G1mySbm8=,tag:m9pclaWF1xWwZQoXfRTBSg==,type:str]
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: ENC[AES256_GCM,data:xS3Oc8K6X7U=,iv:chBCFfr7hyVX5H2tcYwXyDGWL4IO60O/JQ/cv2VKfoc=,tag:w0nFybhfTVKxgdnOGJddzA==,type:str]
type: ENC[AES256_GCM,data:5MpD3PMz,iv:qxG2GjX5PB/loBdtzKC0ngSg8Z2iVXGA7nt7G09GyqA=,tag:4ANqNELJDeFM2ZSjMmjPOw==,type:str]
data:
    grafana-user: ENC[AES256_GCM,data:YO2T6+3qIBc=,iv:kRWKwdnPBqLMMgMC/M/wKVioPn7c11hLSjbvKDS11lw=,tag:sjocNsn7XCUtTRmfyY0JeA==,type:str]
    grafana-password: ENC[AES256_GCM,data:swGWuRLzDVk3c93GXurqjaj4K0mUArCfqGa2YkDiV+EM8KkC,iv:D3hO4KicsadjlJaSBqLTluYBonTBCetuazi2p83mSIk=,tag:GsB5Bfq7tX/o0fU4h6GYdw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jh9mchm2yn0fnz74t8njjagqsq7rem6ezfrz26mvvvnu5dlk7v7ss57cc7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQMGJwT2lpUEppU21YTWJP
            NFlNSzgrbXBVQTBkWUhzbGZXSlJ4cGk1aENJCldVRitXTjY4RVg4ZmVxdkxyRzBM
            NUFGSVRhRG5aRGRWUDkrajZLa1R0NHMKLS0tIEFpVTdidC9POW4wK1R0K1BORVAw
            WEg0YTRPdTVIYUFjNG1QUDBkeTBWNVkKtbLT/JIEbfSimPHd9rV79btet9g2/BrB
            jmZuzCSBlyLn3O/AF8cAZtBDt9J3oclN8PyqhNL/6l0UIaOpTLRROw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-17T12:59:31Z"
    mac: ENC[AES256_GCM,data:FcxKXo/wiVONf4ZQKCgqLvOonycU1aDgvEg981W9p08aPKnrtzoRP8dnaAfKR6GiFu54mYZJUhPZH2TGn+X4lKVxtUxoPNX95R5FA4bvQcXUSsNjzSS40IWc8FkTon2eOD8ndXrG5P8xx8Ki0L0Ntk9cm+/Nmxpw5ZkDd0m7fbc=,iv:rfrFfBvmrqEsRoWKHV0N4fSIFoD0mcI+8xo3UFnnb2E=,tag:MqCHPNRuzn0K5cYLd7LQxw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
