apiVersion: ENC[AES256_GCM,data:6RE=,iv:v07OTqdH+1oFGnCU856dHfmBQ5p+SSTy99z4/IVY+RA=,tag:2CSCN+erk8mm6ihWKtXPLQ==,type:str]
kind: ENC[AES256_GCM,data:9Ng5TODh,iv:Onyn8KWEV2JNEi+CwmORRo4+1dVbs90PZidp5binM14=,tag:mrV4yIE9HgjEUPk149AviA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:P9/X8JmM9TvKjWlAhBG9Vas=,iv:bBlvUW3n7jK7A+Si0H4SZDC4RXc5D2BtQIkdvEbqthY=,tag:GuuNufOz+yK7sb9WqZRigA==,type:str]
    namespace: ENC[AES256_GCM,data:bw8lOEQiNR3JfQ==,iv:M8XF9ja9qJxKrtzPdWp16LLbQR1fkUptbuL+uiUe6Gw=,tag:UmN27InnV+A9kD2+MbNzgA==,type:str]
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: ENC[AES256_GCM,data:PjNVXw==,iv:aR4AffB/txYCCYLScBO3n71iU743RpySiFJUta6lBAM=,tag:mngkWjooCzravgFjKGrQIA==,type:str]
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: ENC[AES256_GCM,data:50h7V1Da4T8=,iv:XAtJya5RQyUL8GRfYFVyXQDjTuEsYVJVt9vRpguBYJc=,tag:I/5+kPJsNybjgCfFpbynPw==,type:str]
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: ENC[AES256_GCM,data:kMGMYw==,iv:a81gTQE102BOJgai4E5QLhe6/xlf4H9khLoPJ1+qGLw=,tag:vSMHgtIMaqwSUGDFWPK79g==,type:str]
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: ENC[AES256_GCM,data:r+yy2NtMinc=,iv:6e7HPN/CjwnWpw0vFqgaGWVEsMbFcHb1YCH50C2Wl2w=,tag:TwfnbGWVbsFFfmjpWc6ruQ==,type:str]
type: ENC[AES256_GCM,data:b9LkLR9X,iv:gu9srrOaQpAiOwI9Cz9bfrlqhVtodY/E4Uv8nZY/eBc=,tag:JLt4VKxPbaU7w0SsDY4A3A==,type:str]
data:
    grafana-user: ENC[AES256_GCM,data:BWAEODFZxVo=,iv:LRv1MSLrhzMGGl/C15Om4ufOQKmP0hm/Jf/1RYOvWO8=,tag:qrz7pFdEBK0pRhqMoHu3yA==,type:str]
    grafana-password: ENC[AES256_GCM,data:HlQ0BElB0NLa9OQi1iEbaaPsvhY=,iv:WMs/id3TF4H2t7Bn+0fEznNjVrRzJQ9WZ5LgVLFwfAI=,tag:4wceqyunx3VPC4HO26coBw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jh9mchm2yn0fnz74t8njjagqsq7rem6ezfrz26mvvvnu5dlk7v7ss57cc7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOdjQ4ZHlsMjE0ZVRXYUNp
            elBnY3NxcU1vdldiNXZqSUZCS0ZYQTdRVHhZCnYvN01OZmhOb01DdTJyaW1iM0lH
            dVpGMW5aMkx4d2FuTEYrWXpOemx4ZjAKLS0tIFJOSVFEOHBoODBidlIwMTBUWk51
            T3o4N3ppdmdDNkZHVFczY081Y3B1RzQKNuwn6cgzqhLGxz/DD/ed82l/G2443spz
            SbXZnsK756aERDOwncvfekFCv0YkVAlmFg+CHnyz0Qbvm4nm04fskw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-17T15:00:07Z"
    mac: ENC[AES256_GCM,data:e2dm383e6wjPnNpVPTOwQnPs7wgX3kNFqRoEhZdimsnkGfOQcHlI9uHj5bIwapU+5k+K22lWEzI6T+XvcaHT39hA4ZI5yrbq7vzgFFUTbkGto++PTOFWTucCy7G+of/enUdEwr8EEEaOuJh43A7quMtJpApxJjUc66aElLEw8gY=,iv:foRXAmkWTc+V7Gjfv9Ep/5kley+Wy7vzGt8llrR97Ho=,tag:cMJNMcAUHOxRKlEQeZmS1Q==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
