apiVersion: ENC[AES256_GCM,data:Yqs=,iv:MM04xXxUeDPoxqtUAtuB32VIxbDrEVtZ/tcIHr3rYVM=,tag:hALS9Lc3j5Oht1rA/eyYtQ==,type:str]
kind: ENC[AES256_GCM,data:GnpPhnFP,iv:wIkxvIqClvY82aY2j85JI9+o+uuQL/AU0Iv1eZZQk3I=,tag:/DyLoHQpV1L3/1KkSn6KNg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:zAExUhfsnZd3kTWP,iv:xIGzdLap7S4thl0ur0/6HhWcOtas3KH/bueSGXd+pf0=,tag:wJGQ742wyFvnmWCTBLyRXQ==,type:str]
    namespace: ENC[AES256_GCM,data:pYptEMu468Y=,iv:ua3ihQIS84OO5LCtquSxxM9TqLe3UqOb8TH6bXqf/go=,tag:/obDUSc1sl/RXcTPkqLH8Q==,type:str]
type: ENC[AES256_GCM,data:efjHhSNT,iv:emf0WNImABLeLReKEKCQ27pcmI8Hxe1In3JhDrYLdF0=,tag:XXi7eMb+ypuNOfLbS9w1Ig==,type:str]
data:
    KK_CLIENT_SECRET_KEY: ENC[AES256_GCM,data:nwzikEpvZg3q42lTfj2kVgeWed6l5BIPDRVzJ8PnHol5aD8jVFT6gc++Ny8=,iv:8gjZ18PTszw6JJANfkEVSyOMLI69o4328ALxk1ZY8Cs=,tag:NUVAJTcK7mXW4RaGj/EcRA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cuu6f3wweappd2xqztvey2d8kxz8a9yfhkzr52t3vw6wz7q6w43suavf89
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2d1hDT3ZnSFRPYmVzSVEx
            TDdxc2RFbGg1emYvSlQ5b1F4Q0s5YXZ6ejFjClFRdlc5ZFlVS1I1d0kzS1dEZnVJ
            QTF5Q3R2ZEdRZGFKdjFLTytKalFKd2MKLS0tIG16VjJTQnZZaWYvN1NSL2YxMzZX
            WTZpdE1DOHhoQzAxVHFpSHd5ZnlqUDgKvzNvyIIIG6JIoeffUVnGYvLJZAc/2Nlk
            UJ1/c6sPusDdVdZ3TjLXdawxpZb2iMprBZNy8huhCN/oV5frvM3uiQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-12T14:31:52Z"
    mac: ENC[AES256_GCM,data:cbNBl7IWRJQpGjJJ3Sc8s5UjfZJ1Rqx9QtUhQIHgP3Gm0hdz83H3BMFDS/f4dbtwMwbfGx1Mfh2fyEqk5wkyCVvlIg5nvpshZboo0Bfgo1jCjcsHTqIfGRZfBi2pCQfc+OCscLgAuvz7+tE5ERwiad9bn1JFsy95A17xiG6lg1o=,iv:PdPhwdfLPWXCYEC1LEN9E1yJNYJzk7luHb9dUaugo8A=,tag:6f9CkVSfWCrqF47pXR1oZw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
